trigger:
  - main

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: study_var

jobs:
  - job: Hello_Terraform
    timeoutInMinutes: 0
    container:
      image: 'hashicorp/terraform'
      options: --entrypoint=""
    steps:
      - script: |
           terraform -version
           ls -aR