trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: study_var

jobs:
  - job: Hello_Terraform
    container:
      image: 'ghcr.io/neilkuantm/azure-pipeline-custom-container-terraform:latest'
    steps:
      - script: |
           echo "Show Terraform Version"
           terraform -version

           echo "Terraform Init"
           terraform init

           echo "Terraform Plan"
           terraform plan
           
           echo "Terraform Apply"
           terraform apply  -auto-approve