trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: study_var

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(STUDY_SUBSCRIPTION_ID)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "hello azure pipeline"
      az account show 
      echo $(System.DefaultWorkingDirectory)