trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: study_var

jobs:
  - job: Hello_Terraform
    container:
      image: 'ghcr.io/neilkuantm/azure-pipeline-custom-container-terraform:latest'
    steps:
      - script: |
           echo "Azure Login"
           az cloud set --name AzureCloud
           
           az az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
           
           echo "Set Subscriptions"
           az account set --subscription "RDSec_Study"
           echo "Show Account"
           az account show

           echo "Terraform Init"
           terraform init

           echo "Terraform Plan"
           terraform plan
           
           echo "Terraform Apply"
           terraform apply  -auto-approve