trigger:
  - main

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: study_var

jobs:
  - job: Hello_Terraform
    timeoutInMinutes: 0
    container:
      image: 'ghcr.io/neilkuantm/azure-pipeline-custom-container-terraform:latest'
      #options: --entrypoint="sh"
    steps:
      - script: |
           terraform -version
           ls -aR