trigger:
  - main

pool:
  vmImage: 'ubuntu-18.04'

variables:
- group: study_var

jobs:
  - job: Hello_Terraform
    timeoutInMinutes: 0
    container:
      image: 'ghcr.io/neilkuantm/azure-pipeline-custom-container-terraform:latest'
    steps:
      - script: |
           terraform -version
           pwd
           ls -aR